const vm=require('node:vm'), fs=require('node:fs'), assert=require('node:assert/strict');
const signup = {};
vm.runInNewContext(fs.readFileSync(__dirname+'/dist/newsletter.js','utf8'),{URL,document:{getElementById:id=>{assert.equal(id,'newsletter-signup');return signup;}}});
assert.equal(signup.target,'_blank');
assert.equal(signup.rel,'noopener noreferrer');
const url=new URL(signup.href);
assert.equal(url.protocol,'https:');
assert.equal(url.hostname,'docs.google.com');
assert.ok(url.pathname.startsWith('/forms/d/e/'));
assert.ok(url.pathname.endsWith('/viewform'));
assert.ok(!signup.href.includes('script.google.com'));
assert.ok(!signup.href.includes('embedded=true'));
console.log('PASS: canonical Google Form signup link.');
