const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname, '..');
const read = name => JSON.parse(fs.readFileSync(path.join(__dirname, name), 'utf8'));
const source = read('organisations.json');
const reference = read('directory-reference.json');
const websites = read('directory-websites.json');
const profiles = read('directory-profiles.json');
const groups = [
  ['Australia', 'Australia'], ['New Zealand', 'New Zealand'],
  ['United Kingdom', 'United Kingdom'], ['Europe', 'Continental Europe'],
  ['United States', 'United States'], ['Canada', 'Canada'], ['Asia', 'Asia'],
  ['Latin America', 'Latin America'], ['Middle East / North Africa', 'Middle East / North Africa'],
  ['Africa', 'Africa'], ['Online / global', 'Online / global']
].map(([id, label]) => ({id, label}));
const europeanCountries = new Set(['Germany', 'Switzerland', 'Austria', 'Sweden', 'Denmark',
  'Norway', 'Italy', 'France', 'Spain', 'Ireland', 'Czech Republic', 'Lithuania', 'Poland', 'Hungary', 'Ukraine']);
const organisations = source.organisations.map((org, index) => {
  const override = reference.overrides[org.name] || {};
  const website = websites.organisations[org.name];
  const profile = profiles.organisations[org.name];
  if (profile === undefined) throw new Error(`Missing organisation profile review: ${org.name}`);
  if (profile) {
    const source = new URL(profile.sourceUrl);
    if (source.protocol !== 'https:' || source.username || source.password || !profile.description?.trim() || profile.description.length > 450) {
      throw new Error(`Invalid organisation profile: ${org.name}`);
    }
  }
  if (website === undefined) throw new Error(`Missing website review: ${org.name}`);
  if (website) {
    const parsed = new URL(website.url);
    if (parsed.protocol !== 'https:' || parsed.username || parsed.password || !['about', 'home'].includes(website.type)) {
      throw new Error(`Unsafe organisation website for ${org.name}`);
    }
  }
  const group = europeanCountries.has(org.region) || org.region === 'Continental Europe' ? 'Europe'
    : org.region === 'Global' || org.region.startsWith('Online / global') ? 'Online / global' : org.region;
  if (!groups.some(entry => entry.id === group)) throw new Error(`Unknown directory region: ${org.region}`);
  const urls = [...new Set([...org.seedUrls, ...(override.referenceUrls || [])])];
  for (const url of urls) {
    const parsed = new URL(url);
    if (parsed.protocol !== 'https:' || parsed.username || parsed.password) throw new Error(`Unsafe reference URL for ${org.name}`);
  }
  return {id: `organisation-${index + 1}`, name: override.name || org.name, group,
    location: europeanCountries.has(org.region) ? org.region : '',
    aliases: [...new Set([org.name, ...(override.aliases || [])])], referenceUrls: urls, website, profile};
});
const registry = {source: reference.source, groups, organisations};
const output = '// Generated by node research/build_directory.cjs. Organisation links do not verify program availability.\nconst radarRegistry = ' + JSON.stringify(registry) + ';\n';
const destination = path.join(root, 'dist/organisations.js');
if (process.argv.includes('--check')) {
  if (!fs.existsSync(destination) || fs.readFileSync(destination, 'utf8').replace(/\r\n/g, '\n') !== output) {
    throw new Error('Directory is out of date. Run node research/build_directory.cjs.');
  }
} else fs.writeFileSync(destination, output);
console.log(`${organisations.length} organisation and resource entries in ${groups.length} regions.`);
