const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const records = JSON.parse(fs.readFileSync(path.join(__dirname, 'runs/2026-09-11/verified-programmes.json'), 'utf8'));
const target = path.join(root, 'dist/app.js');
const source = fs.readFileSync(target, 'utf8');
const boundary = source.indexOf('const typeOrder');
if (!source.startsWith('const opportunities = [') || boundary < 0) throw new Error('Unexpected app data layout');
JSON.parse(source.slice('const opportunities = '.length, boundary).trim().replace(/;$/, ''));
const data = records.map(record => ({ ...record, source: 'Official source reviewed 11 Sep 2026' }));
fs.writeFileSync(target, `const opportunities = ${JSON.stringify(data, null, 2)};\n\n${source.slice(boundary)}`);
console.log(`Synced ${data.length} reviewed programmes.`);
